" Name:         graey
" Description:  A gr[ae]y colorscheme
" Author:       Jaehwang Jung <tomtomjhj@gmail.com>
" Maintainer:   Jaehwang Jung <tomtomjhj@gmail.com>
" License:      Vim License (see `:help license`)

" Generated by Colortemplate v2.2.3

hi clear
let g:colors_name = 'graey'

let s:t_Co = has('gui_running') ? -1 : get(g:, 'graey_t_Co', get(g:, 't_Co', exists('&t_Co') ? +&t_Co : 0))
let s:italics = has('gui_running') || has('nvim') || (&t_ZH != '' && &t_ZH != '[7m' && !has('win32'))

hi! link String Literal
hi! link Character Literal
hi! link Number Literal
hi! link Boolean Literal
hi! link Float Literal
hi! link Function Identifier
hi! link Conditional Statement
hi! link Repeat Statement
hi! link Operator Statement
hi! link Keyword Statement
hi! link Exception Statement
hi! link Include PreProc
hi! link Define PreProc
hi! link PreCondit PreProc
hi! link StorageClass Statement
hi! link Structure Statement
hi! link Typedef Statement
hi! link SpecialChar Special
hi! link Tag Special
hi! link Debug Special
hi! link FloatBorder NormalFloat
hi! link MessageWindow Pmenu
hi! link PopupNotification Todo
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Terminal Normal
hi! link VertSplit WinSeparator
hi! link lCursor Cursor
if has('nvim-0.8')
  hi! link @variable Identifier
  hi! link @variable.builtin Constant
  hi! link @variable.parameter.builtin Constant
  hi! link @constant.builtin Constant
  hi! link @constant.macro Constant
  hi! link @module Identifier
  hi! link @module.builtin Constant
  hi! link @type.builtin Constant
  hi! link @type.definition Label
  hi! link @attribute Special
  hi! link @function Label
  hi! link @function.builtin Constant
  hi! link @function.call Identifier
  hi! link @function.macro Macro
  hi! link @function.method Label
  hi! link @function.method.call Identifier
  hi! link @function.latex Constant
  hi! link @constructor Identifier
  hi! link @punctuation.special PunctuationSpecial
  hi! link @markup.strong Bold
  hi! link @markup.italic Italic
  hi! link @markup.strikethrough Strikethrough
  hi! link @markup.underline Underlined
  hi! link @markup.heading Title
  hi! link @markup.quote NONE
  hi! link @markup.math Literal
  hi! link @markup.link Underlined
  hi! link @markup.raw NormalFloat
  hi! link @markup.list PunctuationSpecial
  hi! link @tag Statement
  hi! link @tag.attribute Identifier
endif
if has('nvim-0.9')
  hi! link @lsp.type.method Identifier
  hi! link @lsp.type.typeParameter Identifier
  hi! link @lsp.type.function Identifier
  hi! link @lsp.type.macro NONE
  hi! link @lsp.type.parameter.python NONE
  hi! link @lsp.typemod.class.declaration Label
  hi! link @lsp.typemod.enum.declaration Label
  hi! link @lsp.typemod.event.declaration Label
  hi! link @lsp.typemod.function.declaration Label
  hi! link @lsp.typemod.interface.declaration Label
  hi! link @lsp.typemod.method.declaration Label
  hi! link @lsp.typemod.namespace.declaration Label
  hi! link @lsp.typemod.struct.declaration Label
  hi! link @lsp.typemod.type.declaration Label
  hi! link @lsp.typemod.class.definition Label
  hi! link @lsp.typemod.enum.definition Label
  hi! link @lsp.typemod.event.definition Label
  hi! link @lsp.typemod.function.definition Label
  hi! link @lsp.typemod.interface.definition Label
  hi! link @lsp.typemod.method.definition Label
  hi! link @lsp.typemod.namespace.definition Label
  hi! link @lsp.typemod.struct.definition Label
  hi! link @lsp.typemod.type.definition Label
  hi! link @lsp.mod.builtin.python Constant
  hi! link @lsp.mod.deduced.cpp Constant
  hi! link @lsp.type.label Identifier
  hi! link @lsp.typemod.label.declaration Label
endif
hi! link debugBreakpoint ModeMsg
hi! link debugPC CursorLine
hi! link diffAdded Added
hi! link diffRemoved Removed
hi! link diffFile Statement
hi! link diffOldFile Label
hi! link diffNewFile Label
hi! link diffIndexLine Comment
if has('nvim')
  hi! link CmpItemAbbrMatch Bold
  hi! link CmpItemKind NONE
endif
hi! link UndotreeBranch NONE
hi! link coqTerm Keyword
hi! link coqTactic Constant
hi! link coqLtac Constant
hi! link coqTacticKwd Constant
hi! link helpCommand Literal
hi! link helpExample Literal
hi! link helpHyperTextJump Underlined
hi! link helpOption Underlined
hi! link htmlBold Bold
hi! link htmlItalic Italic
hi! link htmlBoldItalic BoldItalic
hi! link htmlStrike Strikethrough
hi! link luaFunction Keyword
hi! link markdownCode NormalFloat
hi! link markdownCodeBlock NormalFloat
hi! link markdownHeadingDelimiter Keyword
hi! link markdownListMarker PunctuationSpecial
hi! link markdownHeadingDelimiter PunctuationSpecial
hi! link ocamlModPath NONE
hi! link ocamlFullMod NONE
hi! link ocamlOperator Operator
hi! link pythonBuiltin Constant
hi! link pythonExceptions NONE
hi! link rustCommentLineDoc Comment
hi! link rustModPath NONE
hi! link shCommandSub NONE
hi! link shArithmetic NONE
hi! link shShellVariables NONE
hi! link shSpecial NONE
hi! link shSpecialDQ NONE
hi! link shSpecialSQ NONE
hi! link texCmd Constant
hi! link texCmdType Constant
hi! link texMathDelim Delimiter
hi! link texMathDelimZone PreProc
hi! link texMathEnvArgName PreProc
hi! link texMathZone Literal
hi! link texNewcmdArgName Label
hi! link texPartArgTitle Title
hi! link texTitleArg Title
hi! link texZone Literal
hi! link vimAutoEvent Constant
hi! link vimCommentTitle SpecialComment
hi! link vimEnvvar Constant
hi! link vimOption Constant

if &background ==# 'dark'
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#080808', '#ff7d81', '#73c660', '#e1a103', '#6da4ff', '#da8aec', '#04c5ce', '#d0d0d0', '#626262', '#ffafae', '#8fe47d', '#ffbe3e', '#9dc2ff', '#f0aeff', '#06e6ef', '#eeeeee']
  endif
  if has('nvim')
    let g:terminal_color_0 = '#080808'
    let g:terminal_color_1 = '#ff7d81'
    let g:terminal_color_2 = '#73c660'
    let g:terminal_color_3 = '#e1a103'
    let g:terminal_color_4 = '#6da4ff'
    let g:terminal_color_5 = '#da8aec'
    let g:terminal_color_6 = '#04c5ce'
    let g:terminal_color_7 = '#d0d0d0'
    let g:terminal_color_8 = '#626262'
    let g:terminal_color_9 = '#ffafae'
    let g:terminal_color_10 = '#8fe47d'
    let g:terminal_color_11 = '#ffbe3e'
    let g:terminal_color_12 = '#9dc2ff'
    let g:terminal_color_13 = '#f0aeff'
    let g:terminal_color_14 = '#06e6ef'
    let g:terminal_color_15 = '#eeeeee'
  endif
  hi Normal guifg=#eeeeee guibg=#080808 gui=NONE cterm=NONE
  hi NormalFloat guifg=NONE guibg=#333333 gui=NONE cterm=NONE
  hi Comment guifg=#b7b7b7 guibg=NONE gui=nocombine cterm=nocombine
  hi Constant guifg=#ffffff guibg=NONE gui=italic,nocombine cterm=italic,nocombine
  hi Identifier guifg=#eeeeee guibg=NONE gui=nocombine cterm=nocombine
  hi Statement guifg=#dfdfdf guibg=NONE gui=bold,nocombine cterm=bold,nocombine
  hi Label guifg=#eeeeee guibg=NONE gui=bold,nocombine,underline cterm=bold,nocombine,underline
  hi PreProc guifg=#eeeeee guibg=NONE gui=bold,nocombine cterm=bold,nocombine
  hi Macro guifg=#eeeeee guibg=NONE gui=italic,nocombine,underline cterm=italic,nocombine,underline
  hi Type guifg=#eeeeee guibg=NONE gui=nocombine cterm=nocombine
  hi Special guifg=#eeeeee guibg=NONE gui=bold,italic,nocombine cterm=bold,italic,nocombine
  hi Delimiter guifg=#d0d0d0 guibg=NONE gui=nocombine cterm=nocombine
  hi SpecialComment guifg=#b7b7b7 guibg=NONE gui=bold,nocombine cterm=bold,nocombine
  hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Ignore guifg=#626262 guibg=NONE gui=nocombine cterm=nocombine
  hi Error guifg=#ff005f guibg=#000000 gui=bold,nocombine,reverse cterm=bold,nocombine,reverse
  hi Todo guifg=#00ffaf guibg=#000000 gui=bold,nocombine,reverse cterm=bold,nocombine,reverse
  hi Added guifg=#73c660 guibg=NONE gui=nocombine cterm=nocombine
  hi Changed guifg=#04c5ce guibg=NONE gui=nocombine cterm=nocombine
  hi Removed guifg=#ff7d81 guibg=NONE gui=nocombine cterm=nocombine
  hi ColorColumn guifg=NONE guibg=#222222 gui=NONE cterm=NONE
  hi Conceal guifg=#dfdfdf guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorIM guifg=#000000 guibg=#afff00 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#444444 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#444444 gui=NONE cterm=NONE
  hi CursorLineNr guifg=NONE guibg=#444444 gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#284028 gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#284343 gui=NONE cterm=NONE
  hi DiffDelete guifg=#ff7d81 guibg=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#585828 gui=NONE cterm=NONE
  hi Directory guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi ErrorMsg guifg=NONE guibg=NONE gui=bold,reverse ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi FoldColumn guifg=#626262 guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#d0d0d0 guibg=#222222 gui=NONE cterm=NONE
  hi IncSearch guifg=#ffaf00 guibg=#000000 gui=bold,reverse,underline cterm=bold,reverse,underline
  hi LineNr guifg=#b7b7b7 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#ff00af guibg=NONE gui=bold cterm=bold
  hi ModeMsg guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText guifg=#626262 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=NONE guibg=#404868 gui=NONE cterm=NONE
  hi PmenuExtra guifg=NONE guibg=#404868 gui=NONE cterm=NONE
  hi PmenuKind guifg=NONE guibg=#404868 gui=bold cterm=bold
  hi PmenuSbar guifg=NONE guibg=#626262 gui=NONE cterm=NONE
  hi PmenuSel guifg=NONE guibg=#6a426a gui=NONE cterm=NONE
  hi PmenuExtraSel guifg=NONE guibg=#6a426a gui=NONE cterm=NONE
  hi PmenuKindSel guifg=NONE guibg=#6a426a gui=bold cterm=bold
  hi PmenuThumb guifg=#585828 guibg=#6a426a gui=NONE cterm=NONE
  hi PmenuMatch guifg=NONE guibg=#404868 gui=bold cterm=bold
  hi PmenuMatchSel guifg=NONE guibg=#6a426a gui=bold cterm=bold
  hi Question guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi QuickFixLine guifg=NONE guibg=#6a426a gui=NONE cterm=NONE
  hi Search guifg=#00afff guibg=#000000 gui=bold,reverse cterm=bold,reverse
  hi CurSearch guifg=#aa22aa guibg=#ffffff gui=bold,reverse,underline cterm=bold,reverse,underline
  hi SignColumn guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  if !s:italics
    hi Constant gui=nocombine cterm=nocombine
    hi Macro gui=nocombine,underline cterm=nocombine,underline
    hi Special gui=bold,nocombine cterm=bold,nocombine
  endif
  if has('nvim')
    hi SpecialKey guifg=#ff00af guibg=NONE gui=NONE cterm=NONE
  else
    hi SpecialKey guifg=#626262 guibg=NONE gui=NONE cterm=NONE
  endif
  hi SpellBad guifg=NONE guibg=NONE guisp=#ff7d81 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#6da4ff gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#da8aec gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#04c5ce gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine guifg=#080808 guibg=#eeeeee gui=bold cterm=bold
  hi StatusLineNC guifg=#080808 guibg=#626262 gui=NONE cterm=NONE
  hi TabLine guifg=NONE guibg=#626262 gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#444444 gui=NONE cterm=NONE
  hi TabLineSel guifg=NONE guibg=#080808 gui=bold cterm=bold
  hi Title guifg=#ffffff guibg=NONE gui=bold,underline cterm=bold,underline
  hi Visual guifg=#ffaf00 guibg=#000000 gui=reverse cterm=reverse
  hi VisualNOS guifg=NONE guibg=#444444 gui=NONE cterm=NONE
  hi WarningMsg guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WildMenu guifg=#00afff guibg=NONE gui=bold cterm=bold
  hi WinSeparator guifg=#d0d0d0 guibg=#444444 gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Bold guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Italic guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi BoldItalic guifg=NONE guibg=NONE gui=bold,italic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi Strikethrough guifg=NONE guibg=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
  hi Literal guifg=#d0d0d0 guibg=NONE gui=italic cterm=italic
  hi PunctuationSpecial guifg=#ffffff guibg=NONE gui=bold cterm=bold
  hi LspReferenceText guifg=#d0d0d0 guibg=NONE gui=reverse cterm=reverse
  hi LspReferenceRead guifg=#d0d0d0 guibg=NONE gui=reverse cterm=reverse
  hi LspReferenceWrite guifg=#d0d0d0 guibg=NONE gui=reverse cterm=reverse
  hi LspInlayHint guifg=#b7b7b7 guibg=#222222 gui=NONE cterm=NONE
  hi LspCodeLens guifg=#b7b7b7 guibg=#222222 gui=NONE cterm=NONE
  hi LspCodeLensSeparator guifg=NONE guibg=#222222 gui=bold cterm=bold
  hi DiagnosticError guifg=#ff7d81 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticWarn guifg=#e1a103 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticInfo guifg=#04c5ce guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticHint guifg=#6da4ff guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticOk guifg=#73c660 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticVirtualTextError guifg=#ff7d81 guibg=#222222 gui=NONE cterm=NONE
  hi DiagnosticVirtualTextWarn guifg=#e1a103 guibg=#222222 gui=NONE cterm=NONE
  hi DiagnosticVirtualTextInfo guifg=#04c5ce guibg=#222222 gui=NONE cterm=NONE
  hi DiagnosticVirtualTextHint guifg=#6da4ff guibg=#222222 gui=NONE cterm=NONE
  hi DiagnosticVirtualTextOk guifg=#73c660 guibg=#222222 gui=NONE cterm=NONE
  hi DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#ff7d81 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#e1a103 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#04c5ce gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#6da4ff gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#73c660 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi Sneak guifg=#ffffff guibg=#00afff gui=bold cterm=bold
  hi SneakLabel guifg=#ffffff guibg=#00afff gui=bold cterm=bold
  hi FlashLabel guifg=#000000 guibg=#afff00 gui=bold cterm=bold
  hi FlashBackdrop guifg=#b7b7b7 guibg=NONE gui=NONE cterm=NONE
  hi csvCol1 guifg=#73c660 guibg=NONE gui=NONE cterm=NONE
  hi csvCol2 guifg=#da8aec guibg=NONE gui=NONE cterm=NONE
  hi csvCol3 guifg=#d0d0d0 guibg=NONE gui=NONE cterm=NONE
  hi csvCol4 guifg=#6da4ff guibg=NONE gui=NONE cterm=NONE
  hi csvCol5 guifg=#e1a103 guibg=NONE gui=NONE cterm=NONE
  hi csvCol6 guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
  hi csvCol7 guifg=#ff7d81 guibg=NONE gui=NONE cterm=NONE
  hi csvCol8 guifg=#04c5ce guibg=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Italic gui=NONE cterm=NONE
    hi BoldItalic gui=bold cterm=bold
    hi Literal gui=NONE cterm=NONE
  endif
else
  " Light background
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#eeeeee', '#a52836', '#207400', '#8d6300', '#1f58b6', '#833794', '#017b80', '#3a3a3a', '#9e9e9e', '#d5565d', '#4d9f3a', '#c18a04', '#4983e5', '#af62c1', '#07aab1', '#121212']
  endif
  if has('nvim')
    let g:terminal_color_0 = '#eeeeee'
    let g:terminal_color_1 = '#a52836'
    let g:terminal_color_2 = '#207400'
    let g:terminal_color_3 = '#8d6300'
    let g:terminal_color_4 = '#1f58b6'
    let g:terminal_color_5 = '#833794'
    let g:terminal_color_6 = '#017b80'
    let g:terminal_color_7 = '#3a3a3a'
    let g:terminal_color_8 = '#9e9e9e'
    let g:terminal_color_9 = '#d5565d'
    let g:terminal_color_10 = '#4d9f3a'
    let g:terminal_color_11 = '#c18a04'
    let g:terminal_color_12 = '#4983e5'
    let g:terminal_color_13 = '#af62c1'
    let g:terminal_color_14 = '#07aab1'
    let g:terminal_color_15 = '#121212'
  endif
  hi Normal guifg=#121212 guibg=#eeeeee gui=NONE cterm=NONE
  hi NormalFloat guifg=NONE guibg=#c6c6c6 gui=NONE cterm=NONE
  hi Comment guifg=#626262 guibg=NONE gui=nocombine cterm=nocombine
  hi Constant guifg=#000000 guibg=NONE gui=italic,nocombine cterm=italic,nocombine
  hi Identifier guifg=#121212 guibg=NONE gui=nocombine cterm=nocombine
  hi Statement guifg=#262626 guibg=NONE gui=bold,nocombine cterm=bold,nocombine
  hi Label guifg=#121212 guibg=NONE gui=bold,nocombine,underline cterm=bold,nocombine,underline
  hi PreProc guifg=#121212 guibg=NONE gui=bold,nocombine cterm=bold,nocombine
  hi Macro guifg=#121212 guibg=NONE gui=italic,nocombine,underline cterm=italic,nocombine,underline
  hi Type guifg=#121212 guibg=NONE gui=nocombine cterm=nocombine
  hi Special guifg=#121212 guibg=NONE gui=bold,italic,nocombine cterm=bold,italic,nocombine
  hi Delimiter guifg=#3a3a3a guibg=NONE gui=nocombine cterm=nocombine
  hi SpecialComment guifg=#626262 guibg=NONE gui=bold,nocombine cterm=bold,nocombine
  hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Ignore guifg=#9e9e9e guibg=NONE gui=nocombine cterm=nocombine
  hi Error guifg=#ff005f guibg=#000000 gui=bold,nocombine,reverse cterm=bold,nocombine,reverse
  hi Todo guifg=#00ffaf guibg=#000000 gui=bold,nocombine,reverse cterm=bold,nocombine,reverse
  hi Added guifg=#207400 guibg=NONE gui=nocombine cterm=nocombine
  hi Changed guifg=#017b80 guibg=NONE gui=nocombine cterm=nocombine
  hi Removed guifg=#a52836 guibg=NONE gui=nocombine cterm=nocombine
  hi ColorColumn guifg=NONE guibg=#dadada gui=NONE cterm=NONE
  hi Conceal guifg=#262626 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorIM guifg=#000000 guibg=#afff00 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#b2b2b2 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#b2b2b2 gui=NONE cterm=NONE
  hi CursorLineNr guifg=NONE guibg=#b2b2b2 gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#b7d2b7 gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#afd7d7 gui=NONE cterm=NONE
  hi DiffDelete guifg=#a52836 guibg=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#ddd099 gui=NONE cterm=NONE
  hi Directory guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi ErrorMsg guifg=NONE guibg=NONE gui=bold,reverse ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi FoldColumn guifg=#9e9e9e guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#3a3a3a guibg=#dadada gui=NONE cterm=NONE
  hi IncSearch guifg=#ffaf00 guibg=#000000 gui=bold,reverse,underline cterm=bold,reverse,underline
  hi LineNr guifg=#626262 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#ff00af guibg=NONE gui=bold cterm=bold
  hi ModeMsg guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText guifg=#9e9e9e guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=NONE guibg=#a0afd7 gui=NONE cterm=NONE
  hi PmenuExtra guifg=NONE guibg=#a0afd7 gui=NONE cterm=NONE
  hi PmenuKind guifg=NONE guibg=#a0afd7 gui=bold cterm=bold
  hi PmenuSbar guifg=NONE guibg=#9e9e9e gui=NONE cterm=NONE
  hi PmenuSel guifg=NONE guibg=#d7a0d7 gui=NONE cterm=NONE
  hi PmenuExtraSel guifg=NONE guibg=#d7a0d7 gui=NONE cterm=NONE
  hi PmenuKindSel guifg=NONE guibg=#d7a0d7 gui=bold cterm=bold
  hi PmenuThumb guifg=#ddd099 guibg=#d7a0d7 gui=NONE cterm=NONE
  hi PmenuMatch guifg=NONE guibg=#a0afd7 gui=bold cterm=bold
  hi PmenuMatchSel guifg=NONE guibg=#d7a0d7 gui=bold cterm=bold
  hi Question guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi QuickFixLine guifg=NONE guibg=#d7a0d7 gui=NONE cterm=NONE
  hi Search guifg=#00afff guibg=#000000 gui=bold,reverse cterm=bold,reverse
  hi CurSearch guifg=#ff5fff guibg=#000000 gui=bold,reverse,underline cterm=bold,reverse,underline
  hi SignColumn guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  if !s:italics
    hi Constant gui=nocombine cterm=nocombine
    hi Macro gui=nocombine,underline cterm=nocombine,underline
    hi Special gui=bold,nocombine cterm=bold,nocombine
  endif
  if has('nvim')
    hi SpecialKey guifg=#ff00af guibg=NONE gui=NONE cterm=NONE
  else
    hi SpecialKey guifg=#9e9e9e guibg=NONE gui=NONE cterm=NONE
  endif
  hi SpellBad guifg=NONE guibg=NONE guisp=#a52836 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#1f58b6 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#833794 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#017b80 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine guifg=#eeeeee guibg=#121212 gui=bold cterm=bold
  hi StatusLineNC guifg=#eeeeee guibg=#9e9e9e gui=NONE cterm=NONE
  hi TabLine guifg=NONE guibg=#9e9e9e gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#b2b2b2 gui=NONE cterm=NONE
  hi TabLineSel guifg=NONE guibg=#eeeeee gui=bold cterm=bold
  hi Title guifg=#000000 guibg=NONE gui=bold,underline cterm=bold,underline
  hi Visual guifg=#ffaf00 guibg=#000000 gui=reverse cterm=reverse
  hi VisualNOS guifg=NONE guibg=#b2b2b2 gui=NONE cterm=NONE
  hi WarningMsg guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WildMenu guifg=#00afff guibg=NONE gui=bold cterm=bold
  hi WinSeparator guifg=#3a3a3a guibg=#b2b2b2 gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Bold guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Italic guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi BoldItalic guifg=NONE guibg=NONE gui=bold,italic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi Strikethrough guifg=NONE guibg=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
  hi Literal guifg=#3a3a3a guibg=NONE gui=italic cterm=italic
  hi PunctuationSpecial guifg=#000000 guibg=NONE gui=bold cterm=bold
  hi LspReferenceText guifg=#3a3a3a guibg=NONE gui=reverse cterm=reverse
  hi LspReferenceRead guifg=#3a3a3a guibg=NONE gui=reverse cterm=reverse
  hi LspReferenceWrite guifg=#3a3a3a guibg=NONE gui=reverse cterm=reverse
  hi LspInlayHint guifg=#626262 guibg=#dadada gui=NONE cterm=NONE
  hi LspCodeLens guifg=#626262 guibg=#dadada gui=NONE cterm=NONE
  hi LspCodeLensSeparator guifg=NONE guibg=#dadada gui=bold cterm=bold
  hi DiagnosticError guifg=#a52836 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticWarn guifg=#8d6300 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticInfo guifg=#017b80 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticHint guifg=#1f58b6 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticOk guifg=#207400 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticVirtualTextError guifg=#a52836 guibg=#dadada gui=NONE cterm=NONE
  hi DiagnosticVirtualTextWarn guifg=#8d6300 guibg=#dadada gui=NONE cterm=NONE
  hi DiagnosticVirtualTextInfo guifg=#017b80 guibg=#dadada gui=NONE cterm=NONE
  hi DiagnosticVirtualTextHint guifg=#1f58b6 guibg=#dadada gui=NONE cterm=NONE
  hi DiagnosticVirtualTextOk guifg=#207400 guibg=#dadada gui=NONE cterm=NONE
  hi DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#a52836 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#8d6300 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#017b80 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#1f58b6 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#207400 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi Sneak guifg=#ffffff guibg=#00afff gui=bold cterm=bold
  hi SneakLabel guifg=#ffffff guibg=#00afff gui=bold cterm=bold
  hi FlashLabel guifg=#000000 guibg=#afff00 gui=bold cterm=bold
  hi FlashBackdrop guifg=#626262 guibg=NONE gui=NONE cterm=NONE
  hi csvCol1 guifg=#207400 guibg=NONE gui=NONE cterm=NONE
  hi csvCol2 guifg=#833794 guibg=NONE gui=NONE cterm=NONE
  hi csvCol3 guifg=#3a3a3a guibg=NONE gui=NONE cterm=NONE
  hi csvCol4 guifg=#1f58b6 guibg=NONE gui=NONE cterm=NONE
  hi csvCol5 guifg=#8d6300 guibg=NONE gui=NONE cterm=NONE
  hi csvCol6 guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi csvCol7 guifg=#a52836 guibg=NONE gui=NONE cterm=NONE
  hi csvCol8 guifg=#017b80 guibg=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Italic gui=NONE cterm=NONE
    hi BoldItalic gui=bold cterm=bold
    hi Literal gui=NONE cterm=NONE
  endif
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    hi Normal ctermfg=255 ctermbg=232 cterm=NONE
    hi NormalFloat ctermfg=NONE ctermbg=236 cterm=NONE
    hi Comment ctermfg=250 ctermbg=NONE cterm=nocombine
    hi Constant ctermfg=231 ctermbg=NONE cterm=italic,nocombine
    hi Identifier ctermfg=255 ctermbg=NONE cterm=nocombine
    hi Statement ctermfg=254 ctermbg=NONE cterm=bold,nocombine
    hi Label ctermfg=255 ctermbg=NONE cterm=bold,nocombine,underline
    hi PreProc ctermfg=255 ctermbg=NONE cterm=bold,nocombine
    hi Macro ctermfg=255 ctermbg=NONE cterm=italic,nocombine,underline
    hi Type ctermfg=255 ctermbg=NONE cterm=nocombine
    hi Special ctermfg=255 ctermbg=NONE cterm=bold,italic,nocombine
    hi Delimiter ctermfg=252 ctermbg=NONE cterm=nocombine
    hi SpecialComment ctermfg=250 ctermbg=NONE cterm=bold,nocombine
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi Ignore ctermfg=241 ctermbg=NONE cterm=nocombine
    hi Error ctermfg=197 ctermbg=16 cterm=bold,nocombine,reverse
    hi Todo ctermfg=49 ctermbg=16 cterm=bold,nocombine,reverse
    hi Added ctermfg=77 ctermbg=NONE cterm=nocombine
    hi Changed ctermfg=44 ctermbg=NONE cterm=nocombine
    hi Removed ctermfg=210 ctermbg=NONE cterm=nocombine
    hi ColorColumn ctermfg=NONE ctermbg=235 cterm=NONE
    hi Conceal ctermfg=254 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi CursorIM ctermfg=16 ctermbg=154 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=238 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=238 cterm=NONE
    hi CursorLineNr ctermfg=NONE ctermbg=238 cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=22 cterm=NONE
    hi DiffChange ctermfg=NONE ctermbg=23 cterm=NONE
    hi DiffDelete ctermfg=210 ctermbg=NONE cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=58 cterm=NONE
    hi Directory ctermfg=NONE ctermbg=NONE cterm=bold
    hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=bold,reverse
    hi FoldColumn ctermfg=241 ctermbg=NONE cterm=NONE
    hi Folded ctermfg=252 ctermbg=235 cterm=NONE
    hi IncSearch ctermfg=214 ctermbg=16 cterm=bold,reverse,underline
    hi LineNr ctermfg=250 ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=199 ctermbg=NONE cterm=bold
    hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi NonText ctermfg=241 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=NONE ctermbg=60 cterm=NONE
    hi PmenuExtra ctermfg=NONE ctermbg=60 cterm=NONE
    hi PmenuKind ctermfg=NONE ctermbg=60 cterm=bold
    hi PmenuSbar ctermfg=NONE ctermbg=241 cterm=NONE
    hi PmenuSel ctermfg=NONE ctermbg=96 cterm=NONE
    hi PmenuExtraSel ctermfg=NONE ctermbg=96 cterm=NONE
    hi PmenuKindSel ctermfg=NONE ctermbg=96 cterm=bold
    hi PmenuThumb ctermfg=58 ctermbg=96 cterm=NONE
    hi PmenuMatch ctermfg=NONE ctermbg=60 cterm=bold
    hi PmenuMatchSel ctermfg=NONE ctermbg=96 cterm=bold
    hi Question ctermfg=NONE ctermbg=NONE cterm=bold
    hi QuickFixLine ctermfg=NONE ctermbg=96 cterm=NONE
    hi Search ctermfg=39 ctermbg=16 cterm=bold,reverse
    hi CurSearch ctermfg=127 ctermbg=231 cterm=bold,reverse,underline
    hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    if !s:italics
      hi Constant cterm=nocombine
      hi Macro cterm=nocombine,underline
      hi Special cterm=bold,nocombine
    endif
    if has('nvim')
      hi SpecialKey ctermfg=199 ctermbg=NONE cterm=NONE
    else
      hi SpecialKey ctermfg=241 ctermbg=NONE cterm=NONE
    endif
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi StatusLine ctermfg=232 ctermbg=255 cterm=bold
    hi StatusLineNC ctermfg=232 ctermbg=241 cterm=NONE
    hi TabLine ctermfg=NONE ctermbg=241 cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=238 cterm=NONE
    hi TabLineSel ctermfg=NONE ctermbg=232 cterm=bold
    hi Title ctermfg=231 ctermbg=NONE cterm=bold,underline
    hi Visual ctermfg=214 ctermbg=16 cterm=reverse
    hi VisualNOS ctermfg=NONE ctermbg=238 cterm=NONE
    hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=39 ctermbg=NONE cterm=bold
    hi WinSeparator ctermfg=252 ctermbg=238 cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold
    hi Bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi Italic ctermfg=NONE ctermbg=NONE cterm=italic
    hi BoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
    hi Strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
    hi Literal ctermfg=252 ctermbg=NONE cterm=italic
    hi PunctuationSpecial ctermfg=231 ctermbg=NONE cterm=bold
    hi LspReferenceText ctermfg=252 ctermbg=NONE cterm=reverse
    hi LspReferenceRead ctermfg=252 ctermbg=NONE cterm=reverse
    hi LspReferenceWrite ctermfg=252 ctermbg=NONE cterm=reverse
    hi LspInlayHint ctermfg=250 ctermbg=235 cterm=NONE
    hi LspCodeLens ctermfg=250 ctermbg=235 cterm=NONE
    hi LspCodeLensSeparator ctermfg=NONE ctermbg=235 cterm=bold
    hi DiagnosticError ctermfg=210 ctermbg=NONE cterm=NONE
    hi DiagnosticWarn ctermfg=214 ctermbg=NONE cterm=NONE
    hi DiagnosticInfo ctermfg=44 ctermbg=NONE cterm=NONE
    hi DiagnosticHint ctermfg=111 ctermbg=NONE cterm=NONE
    hi DiagnosticOk ctermfg=77 ctermbg=NONE cterm=NONE
    hi DiagnosticVirtualTextError ctermfg=210 ctermbg=235 cterm=NONE
    hi DiagnosticVirtualTextWarn ctermfg=214 ctermbg=235 cterm=NONE
    hi DiagnosticVirtualTextInfo ctermfg=44 ctermbg=235 cterm=NONE
    hi DiagnosticVirtualTextHint ctermfg=111 ctermbg=235 cterm=NONE
    hi DiagnosticVirtualTextOk ctermfg=77 ctermbg=235 cterm=NONE
    hi DiagnosticUnderlineError ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineWarn ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineHint ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineOk ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi Sneak ctermfg=231 ctermbg=39 cterm=bold
    hi SneakLabel ctermfg=231 ctermbg=39 cterm=bold
    hi FlashLabel ctermfg=16 ctermbg=154 cterm=bold
    hi FlashBackdrop ctermfg=250 ctermbg=NONE cterm=NONE
    hi csvCol1 ctermfg=77 ctermbg=NONE cterm=NONE
    hi csvCol2 ctermfg=177 ctermbg=NONE cterm=NONE
    hi csvCol3 ctermfg=252 ctermbg=NONE cterm=NONE
    hi csvCol4 ctermfg=111 ctermbg=NONE cterm=NONE
    hi csvCol5 ctermfg=214 ctermbg=NONE cterm=NONE
    hi csvCol6 ctermfg=231 ctermbg=NONE cterm=NONE
    hi csvCol7 ctermfg=210 ctermbg=NONE cterm=NONE
    hi csvCol8 ctermfg=44 ctermbg=NONE cterm=NONE
    if !s:italics
      hi Italic cterm=NONE
      hi BoldItalic cterm=bold
      hi Literal cterm=NONE
    endif
  else
    " Light background
    hi Normal ctermfg=233 ctermbg=255 cterm=NONE
    hi NormalFloat ctermfg=NONE ctermbg=251 cterm=NONE
    hi Comment ctermfg=241 ctermbg=NONE cterm=nocombine
    hi Constant ctermfg=16 ctermbg=NONE cterm=italic,nocombine
    hi Identifier ctermfg=233 ctermbg=NONE cterm=nocombine
    hi Statement ctermfg=235 ctermbg=NONE cterm=bold,nocombine
    hi Label ctermfg=233 ctermbg=NONE cterm=bold,nocombine,underline
    hi PreProc ctermfg=233 ctermbg=NONE cterm=bold,nocombine
    hi Macro ctermfg=233 ctermbg=NONE cterm=italic,nocombine,underline
    hi Type ctermfg=233 ctermbg=NONE cterm=nocombine
    hi Special ctermfg=233 ctermbg=NONE cterm=bold,italic,nocombine
    hi Delimiter ctermfg=237 ctermbg=NONE cterm=nocombine
    hi SpecialComment ctermfg=241 ctermbg=NONE cterm=bold,nocombine
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi Ignore ctermfg=247 ctermbg=NONE cterm=nocombine
    hi Error ctermfg=197 ctermbg=16 cterm=bold,nocombine,reverse
    hi Todo ctermfg=49 ctermbg=16 cterm=bold,nocombine,reverse
    hi Added ctermfg=28 ctermbg=NONE cterm=nocombine
    hi Changed ctermfg=30 ctermbg=NONE cterm=nocombine
    hi Removed ctermfg=124 ctermbg=NONE cterm=nocombine
    hi ColorColumn ctermfg=NONE ctermbg=253 cterm=NONE
    hi Conceal ctermfg=235 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi CursorIM ctermfg=16 ctermbg=154 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=249 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=249 cterm=NONE
    hi CursorLineNr ctermfg=NONE ctermbg=249 cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=151 cterm=NONE
    hi DiffChange ctermfg=NONE ctermbg=152 cterm=NONE
    hi DiffDelete ctermfg=124 ctermbg=NONE cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=186 cterm=NONE
    hi Directory ctermfg=NONE ctermbg=NONE cterm=bold
    hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=bold,reverse
    hi FoldColumn ctermfg=247 ctermbg=NONE cterm=NONE
    hi Folded ctermfg=237 ctermbg=253 cterm=NONE
    hi IncSearch ctermfg=214 ctermbg=16 cterm=bold,reverse,underline
    hi LineNr ctermfg=241 ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=199 ctermbg=NONE cterm=bold
    hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi NonText ctermfg=247 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=NONE ctermbg=146 cterm=NONE
    hi PmenuExtra ctermfg=NONE ctermbg=146 cterm=NONE
    hi PmenuKind ctermfg=NONE ctermbg=146 cterm=bold
    hi PmenuSbar ctermfg=NONE ctermbg=247 cterm=NONE
    hi PmenuSel ctermfg=NONE ctermbg=176 cterm=NONE
    hi PmenuExtraSel ctermfg=NONE ctermbg=176 cterm=NONE
    hi PmenuKindSel ctermfg=NONE ctermbg=176 cterm=bold
    hi PmenuThumb ctermfg=186 ctermbg=176 cterm=NONE
    hi PmenuMatch ctermfg=NONE ctermbg=146 cterm=bold
    hi PmenuMatchSel ctermfg=NONE ctermbg=176 cterm=bold
    hi Question ctermfg=NONE ctermbg=NONE cterm=bold
    hi QuickFixLine ctermfg=NONE ctermbg=176 cterm=NONE
    hi Search ctermfg=39 ctermbg=16 cterm=bold,reverse
    hi CurSearch ctermfg=207 ctermbg=16 cterm=bold,reverse,underline
    hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    if !s:italics
      hi Constant cterm=nocombine
      hi Macro cterm=nocombine,underline
      hi Special cterm=bold,nocombine
    endif
    if has('nvim')
      hi SpecialKey ctermfg=199 ctermbg=NONE cterm=NONE
    else
      hi SpecialKey ctermfg=247 ctermbg=NONE cterm=NONE
    endif
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi StatusLine ctermfg=255 ctermbg=233 cterm=bold
    hi StatusLineNC ctermfg=255 ctermbg=247 cterm=NONE
    hi TabLine ctermfg=NONE ctermbg=247 cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=249 cterm=NONE
    hi TabLineSel ctermfg=NONE ctermbg=255 cterm=bold
    hi Title ctermfg=16 ctermbg=NONE cterm=bold,underline
    hi Visual ctermfg=214 ctermbg=16 cterm=reverse
    hi VisualNOS ctermfg=NONE ctermbg=249 cterm=NONE
    hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=39 ctermbg=NONE cterm=bold
    hi WinSeparator ctermfg=237 ctermbg=249 cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold
    hi Bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi Italic ctermfg=NONE ctermbg=NONE cterm=italic
    hi BoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
    hi Strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
    hi Literal ctermfg=237 ctermbg=NONE cterm=italic
    hi PunctuationSpecial ctermfg=16 ctermbg=NONE cterm=bold
    hi LspReferenceText ctermfg=237 ctermbg=NONE cterm=reverse
    hi LspReferenceRead ctermfg=237 ctermbg=NONE cterm=reverse
    hi LspReferenceWrite ctermfg=237 ctermbg=NONE cterm=reverse
    hi LspInlayHint ctermfg=241 ctermbg=253 cterm=NONE
    hi LspCodeLens ctermfg=241 ctermbg=253 cterm=NONE
    hi LspCodeLensSeparator ctermfg=NONE ctermbg=253 cterm=bold
    hi DiagnosticError ctermfg=124 ctermbg=NONE cterm=NONE
    hi DiagnosticWarn ctermfg=94 ctermbg=NONE cterm=NONE
    hi DiagnosticInfo ctermfg=30 ctermbg=NONE cterm=NONE
    hi DiagnosticHint ctermfg=26 ctermbg=NONE cterm=NONE
    hi DiagnosticOk ctermfg=28 ctermbg=NONE cterm=NONE
    hi DiagnosticVirtualTextError ctermfg=124 ctermbg=253 cterm=NONE
    hi DiagnosticVirtualTextWarn ctermfg=94 ctermbg=253 cterm=NONE
    hi DiagnosticVirtualTextInfo ctermfg=30 ctermbg=253 cterm=NONE
    hi DiagnosticVirtualTextHint ctermfg=26 ctermbg=253 cterm=NONE
    hi DiagnosticVirtualTextOk ctermfg=28 ctermbg=253 cterm=NONE
    hi DiagnosticUnderlineError ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineWarn ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineHint ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineOk ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi Sneak ctermfg=231 ctermbg=39 cterm=bold
    hi SneakLabel ctermfg=231 ctermbg=39 cterm=bold
    hi FlashLabel ctermfg=16 ctermbg=154 cterm=bold
    hi FlashBackdrop ctermfg=241 ctermbg=NONE cterm=NONE
    hi csvCol1 ctermfg=28 ctermbg=NONE cterm=NONE
    hi csvCol2 ctermfg=90 ctermbg=NONE cterm=NONE
    hi csvCol3 ctermfg=237 ctermbg=NONE cterm=NONE
    hi csvCol4 ctermfg=26 ctermbg=NONE cterm=NONE
    hi csvCol5 ctermfg=94 ctermbg=NONE cterm=NONE
    hi csvCol6 ctermfg=16 ctermbg=NONE cterm=NONE
    hi csvCol7 ctermfg=124 ctermbg=NONE cterm=NONE
    hi csvCol8 ctermfg=30 ctermbg=NONE cterm=NONE
    if !s:italics
      hi Italic cterm=NONE
      hi BoldItalic cterm=bold
      hi Literal cterm=NONE
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 16
  if has('nvim-0.8')
    hi! link @markup.raw Comment
  endif
  hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NormalFloat ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Comment ctermfg=8 ctermbg=NONE cterm=bold
  hi Constant ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Statement ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Label ctermfg=NONE ctermbg=NONE cterm=bold
  hi PreProc ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Macro ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Type ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Special ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=NONE ctermbg=NONE cterm=italic
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Error ctermfg=darkred ctermbg=NONE cterm=bold,reverse
  hi Todo ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Added ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi Changed ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi Removed ctermfg=darkred ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=8 ctermbg=NONE cterm=reverse
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorLineNr ctermfg=NONE ctermbg=NONE cterm=bold
  hi DiffAdd ctermfg=darkgreen ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=darkblue ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=darkred ctermbg=NONE cterm=NONE
  hi DiffText ctermfg=darkmagenta ctermbg=NONE cterm=reverse
  hi Directory ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi FoldColumn ctermfg=8 ctermbg=NONE cterm=reverse
  hi Folded ctermfg=NONE ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=darkyellow ctermbg=NONE cterm=bold,reverse,underline
  hi LineNr ctermfg=8 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText ctermfg=8 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=NONE ctermbg=8 cterm=NONE
  hi PmenuExtra ctermfg=NONE ctermbg=8 cterm=NONE
  hi PmenuKind ctermfg=NONE ctermbg=8 cterm=bold
  hi PmenuMatch ctermfg=NONE ctermbg=8 cterm=bold
  hi PmenuSbar ctermfg=NONE ctermbg=8 cterm=NONE
  hi PmenuSel ctermfg=NONE ctermbg=NONE cterm=bold,reverse,underline
  hi PmenuExtraSel ctermfg=NONE ctermbg=NONE cterm=bold,reverse,underline
  hi PmenuKindSel ctermfg=NONE ctermbg=NONE cterm=bold,reverse,underline
  hi PmenuMatchSel ctermfg=NONE ctermbg=NONE cterm=bold,reverse,underline
  hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question ctermfg=NONE ctermbg=NONE cterm=bold
  hi QuickFixLine ctermfg=darkmagenta ctermbg=NONE cterm=reverse
  hi Search ctermfg=darkcyan ctermbg=NONE cterm=bold,reverse
  hi CurSearch ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse,underline
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  if !s:italics
    hi SpecialComment cterm=NONE
  endif
  if has('nvim')
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  else
    hi SpellBad ctermfg=darkred ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=darkblue ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=darkmagenta ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=darkcyan ctermbg=NONE cterm=undercurl
  endif
  hi StatusLine ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi StatusLineNC ctermfg=8 ctermbg=NONE cterm=bold,reverse
  hi TabLine ctermfg=NONE ctermbg=8 cterm=nocombine
  hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=underline
  hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=bold,nocombine
  hi Title ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi VertSplit ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual ctermfg=darkyellow ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=standout
  hi WildMenu ctermfg=NONE ctermbg=NONE cterm=bold
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi BoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi Strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
  hi Literal ctermfg=NONE ctermbg=NONE cterm=italic
  hi PunctuationSpecial ctermfg=NONE ctermbg=NONE cterm=bold
  hi LspReferenceText ctermfg=8 ctermbg=NONE cterm=reverse
  hi LspReferenceRead ctermfg=8 ctermbg=NONE cterm=reverse
  hi LspReferenceWrite ctermfg=8 ctermbg=NONE cterm=reverse
  hi LspInlayHint ctermfg=8 ctermbg=NONE cterm=reverse
  hi LspCodeLens ctermfg=8 ctermbg=NONE cterm=reverse
  hi LspCodeLensSeparator ctermfg=8 ctermbg=NONE cterm=bold,reverse
  hi DiagnosticError ctermfg=darkred ctermbg=NONE cterm=NONE
  hi DiagnosticWarn ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi DiagnosticInfo ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi DiagnosticHint ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi DiagnosticOk ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi DiagnosticUnderlineError ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineWarn ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineHint ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineOk ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi Sneak ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi SneakLabel ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi FlashLabel ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi FlashBackdrop ctermfg=NONE ctermbg=NONE cterm=NONE
  if !s:italics
    hi Italic cterm=NONE
    hi BoldItalic cterm=bold
    hi Literal cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if has('nvim-0.8')
    hi! link @markup.raw Comment
  endif
  hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NormalFloat ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Comment ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi Constant ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Statement ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Label ctermfg=NONE ctermbg=NONE cterm=bold
  hi PreProc ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Macro ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Type ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Special ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=NONE ctermbg=NONE cterm=italic
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Error ctermfg=darkred ctermbg=NONE cterm=bold,reverse
  hi Todo ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Added ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi Changed ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi Removed ctermfg=darkred ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorLineNr ctermfg=NONE ctermbg=NONE cterm=bold
  hi DiffAdd ctermfg=darkgreen ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=darkblue ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=darkred ctermbg=NONE cterm=NONE
  hi DiffText ctermfg=darkmagenta ctermbg=NONE cterm=reverse
  hi Directory ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Folded ctermfg=NONE ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=darkyellow ctermbg=NONE cterm=bold,reverse,underline
  hi LineNr ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuExtra ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuKind ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi PmenuMatch ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuSel ctermfg=NONE ctermbg=NONE cterm=bold,reverse,underline
  hi PmenuExtraSel ctermfg=NONE ctermbg=NONE cterm=bold,reverse,underline
  hi PmenuKindSel ctermfg=NONE ctermbg=NONE cterm=bold,reverse,underline
  hi PmenuMatchSel ctermfg=NONE ctermbg=NONE cterm=bold,reverse,underline
  hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question ctermfg=NONE ctermbg=NONE cterm=bold
  hi QuickFixLine ctermfg=darkmagenta ctermbg=NONE cterm=reverse
  hi Search ctermfg=darkcyan ctermbg=NONE cterm=bold,reverse
  hi CurSearch ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse,underline
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  if !s:italics
    hi Comment cterm=bold
    hi SpecialComment cterm=NONE
  endif
  if has('nvim')
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  else
    hi SpellBad ctermfg=darkred ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=darkblue ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=darkmagenta ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=darkcyan ctermbg=NONE cterm=undercurl
  endif
  hi StatusLine ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi StatusLineNC ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi TabLine ctermfg=NONE ctermbg=NONE cterm=nocombine,reverse
  hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=underline
  hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=bold,nocombine
  hi Title ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi VertSplit ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual ctermfg=darkyellow ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=standout
  hi WildMenu ctermfg=NONE ctermbg=NONE cterm=bold
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi BoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi Strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
  hi Literal ctermfg=NONE ctermbg=NONE cterm=italic
  hi PunctuationSpecial ctermfg=NONE ctermbg=NONE cterm=bold
  hi LspReferenceText ctermfg=NONE ctermbg=NONE cterm=reverse
  hi LspReferenceRead ctermfg=NONE ctermbg=NONE cterm=reverse
  hi LspReferenceWrite ctermfg=NONE ctermbg=NONE cterm=reverse
  hi LspInlayHint ctermfg=NONE ctermbg=NONE cterm=reverse
  hi LspCodeLens ctermfg=NONE ctermbg=NONE cterm=reverse
  hi LspCodeLensSeparator ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi DiagnosticError ctermfg=darkred ctermbg=NONE cterm=NONE
  hi DiagnosticWarn ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi DiagnosticInfo ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi DiagnosticHint ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi DiagnosticOk ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi DiagnosticUnderlineError ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineWarn ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineHint ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineOk ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi Sneak ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi SneakLabel ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi FlashLabel ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi FlashBackdrop ctermfg=NONE ctermbg=NONE cterm=NONE
  if !s:italics
    hi Italic cterm=NONE
    hi BoldItalic cterm=bold
    hi Literal cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi NormalFloat term=reverse
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=reverse
  hi CursorColumn term=NONE
  hi CursorLine term=underline
  hi CursorLineNr term=bold
  hi DiffAdd term=reverse
  hi DiffChange term=NONE
  hi DiffDelete term=reverse
  hi DiffText term=reverse
  hi Directory term=NONE
  hi ErrorMsg term=bold,reverse
  hi FoldColumn term=NONE
  hi Folded term=NONE
  hi IncSearch term=bold,reverse,underline
  hi LineNr term=NONE
  hi MatchParen term=bold,underline
  hi ModeMsg term=bold
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=reverse
  hi PmenuSel term=bold
  hi PmenuThumb term=NONE
  hi Question term=bold
  hi Search term=reverse
  hi SignColumn term=reverse
  hi SpellBad term=underline
  hi SpellCap term=underline
  hi SpellLocal term=underline
  hi SpellRare term=underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=bold,underline
  hi TabLine term=bold,underline
  hi TabLineFill term=NONE
  hi Terminal term=NONE
  hi TabLineSel term=bold,reverse
  hi Title term=NONE
  hi VertSplit term=NONE
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  hi CurSearch term=reverse
  hi CursorLineFold term=underline
  hi CursorLineSign term=underline
  hi Comment term=bold
  hi Constant term=NONE
  hi Error term=bold,reverse
  hi Identifier term=NONE
  hi Ignore term=NONE
  hi PreProc term=NONE
  hi Special term=NONE
  hi Statement term=NONE
  hi Todo term=bold,reverse
  hi Type term=NONE
  hi Underlined term=underline
  unlet s:t_Co s:italics
  finish
endif

" Color: black         #000000           16
" Color: white         #ffffff           231
" Background: dark
" Color: fg_1          #ffffff           231
" Color: fg0           #eeeeee           255
" Color: fg05          #dfdfdf           254
" Color: fg1           #d0d0d0           252
" Color: fg2           #b7b7b7           250
" Color: bg0           #080808           232
" Color: bg1           #222222           235
" Color: bg2           #333333           236
" Color: bg3           #444444           238
" Color: bg4           #626262           241
" Color: quite1        #ff7d81           210 ; oklch(74% 0.1586 20)
" Color: quite2        #73c660           77  ; oklch(75% 0.16   140)
" Color: quite3        #e1a103           214 ; oklch(75% 0.1548 80)
" Color: quite4        #6da4ff           111 ; oklch(72% 0.1456 260)
" Color: quite5        #da8aec           177 ; oklch(75% 0.16   320)
" Color: quite6        #04c5ce           44  ; oklch(75% 0.1271 200)
" Color: quite9        #ffafae           217 ; oklch(83% 0.0939 20)
" Color: quite10       #8fe47d           113 ; oklch(84% 0.16   140)
" Color: quite11       #ffbe3e           214 ; oklch(84% 0.1548 80)
" Color: quite12       #9dc2ff           111 ; oklch(81% 0.095  260)
" Color: quite13       #f0aeff           219 ; oklch(84% 0.1293 320)
" Color: quite14       #06e6ef           44  ; oklch(84% 0.1423 200)
" Color: bggreen       #284028           22  ; oklch(34.42% 0.0509 144.37)
" Color: bgblue        #404868           60  ; oklch(40.86% 0.0549 272.99)
" Color: bgpink        #6a426a           96  ; oklch(44% 0.08 326.9)
" Color: bgyellow      #585828           58  ; oklch(47.74% 0.0685 108.74)
" Color: bgcyan        #284343           23  ; oklch(36% 0.033 195.98)
" Color: uipink        #ff00af           199
" Color: uilime        #afff00           154
" Color: uiteal        #00ffaf           49
" Color: uiblue        #00afff           39
" Color: uipurple      #af00ff           129
" Color: uiamber       #ffaf00           214
" Color: uicursearch   #aa22aa           127
" Color: errorred      #ff005f           197
" Term colors: bg0
" Term colors: quite1 quite2 quite3 quite4 quite5 quite6
" Term colors: fg1
" Term colors: bg4
" Term colors: quite9 quite10 quite11 quite12 quite13 quite14
" Term colors: fg0
" Background: light
" Color: fg_1          #000000           16
" Color: fg0           #121212           233
" Color: fg05          #262626           235
" Color: fg1           #3a3a3a           237
" Color: fg2           #626262           241
" Color: bg0           #eeeeee           255
" Color: bg1           #dadada           253
" Color: bg2           #c6c6c6           251
" Color: bg3           #b2b2b2           249
" Color: bg4           #9e9e9e           247
" Color: quite1        #a52836           124 ; oklch(48% 0.16   20)
" Color: quite2        #207400           28  ; oklch(49% 0.1575 140)
" Color: quite3        #8d6300           94  ; oklch(53% 0.1097 80)
" Color: quite4        #1f58b6           26  ; oklch(48% 0.16   260)
" Color: quite5        #833794           90  ; oklch(48% 0.16   320)
" Color: quite6        #017b80           30  ; oklch(53% 0.09   200)
" Color: quite9        #d5565d           167 ; oklch(62% 0.16  20)
" Color: quite10       #4d9f3a           71  ; oklch(63% 0.16  140)
" Color: quite11       #c18a04           136 ; oklch(67% 0.138 80)
" Color: quite12       #4983e5           68  ; oklch(62% 0.16  260)
" Color: quite13       #af62c1           133 ; oklch(62% 0.16  320)
" Color: quite14       #07aab1           37  ; oklch(67% 0.113 200)
" Color: bggreen       #b7d2b7           151 ; oklch(83.63% 0.0471 145.14)
" Color: bgblue        #a0afd7           146 ; oklch(75.62% 0.0601 268.85)
" Color: bgpink        #d7a0d7           176 ; oklch(77.5% 0.0976 326.47)
" Color: bgyellow      #ddd099           186 ; oklch(85.5% 0.0731 96.41)
" Color: bgcyan        #afd7d7           152 ; oklch(85.06% 0.042 196.39)
" Color: uipink        #ff00af           199
" Color: uilime        #afff00           154
" Color: uiteal        #00ffaf           49
" Color: uiblue        #00afff           39
" Color: uipurple      #af00ff           129
" Color: uiamber       #ffaf00           214
" Color: uicursearch   #ff5fff           207
" Color: errorred      #ff005f           197
" Term colors: bg0
" Term colors: quite1 quite2 quite3 quite4 quite5 quite6
" Term colors: fg1
" Term colors: bg4
" Term colors: quite9 quite10 quite11 quite12 quite13 quite14
" Term colors: fg0
" Background: any
" Color: term1         #ff7d81           210               darkred
" Color: term2         #73c660           77                darkgreen
" Color: term3         #e1a103           214               darkyellow
" Color: term4         #6da4ff           111               darkblue
" Color: term5         #da8aec           177               darkmagenta
" Color: term6         #04c5ce           44                darkcyan
" Color: term8         #808080           8                 8  ; darkgrey
" vim: et ts=8 sw=2 sts=2
