" Name:         quite
" Description:  A colorscheme derived from neutaaaaan's "quiet"
" Author:       Jaehwang Jung <tomtomjhj@gmail.com>
" Maintainer:   Jaehwang Jung <tomtomjhj@gmail.com>
" License:      Vim License (see `:help license`)

" Generated by Colortemplate v2.2.3

hi clear
let g:colors_name = 'quite'

let s:t_Co = has('gui_running') ? -1 : get(g:, 'quite_t_Co', get(g:, 't_Co', exists('&t_Co') ? +&t_Co : 0))
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link String Literal
hi! link Character Literal
hi! link Number Literal
hi! link Boolean Literal
hi! link Float Literal
hi! link Function Identifier
hi! link Conditional Statement
hi! link Repeat Statement
hi! link Operator Statement
hi! link Keyword Statement
hi! link Exception Statement
hi! link Include PreProc
hi! link Define PreProc
hi! link PreCondit PreProc
hi! link StorageClass Statement
hi! link Structure Statement
hi! link Typedef Statement
hi! link SpecialChar Special
hi! link Tag Special
hi! link Debug Special
hi! link FloatBorder NormalFloat
hi! link MessageWindow Pmenu
hi! link PopupNotification Todo
if has('nvim')
  hi! link SpecialKey Special
else
  hi! link SpecialKey NonText
endif
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Terminal Normal
hi! link VertSplit WinSeparator
hi! link lCursor Cursor
if has('nvim-0.8')
  hi! link @variable Identifier
  hi! link @variable.builtin Constant
  hi! link @constant.builtin Constant
  hi! link @constant.macro Constant
  hi! link @module NONE
  hi! link @module.builtin Constant
  hi! link @type.builtin Constant
  hi! link @type.definition Label
  hi! link @attribute Special
  hi! link @function Label
  hi! link @function.builtin Constant
  hi! link @function.call NONE
  hi! link @function.macro Macro
  hi! link @function.method Label
  hi! link @function.method.call NONE
  hi! link @function.latex Constant
  hi! link @constructor NONE
  hi! link @punctuation.special PunctuationSpecial
  hi! link @markup.strong Bold
  hi! link @markup.italic Italic
  hi! link @markup.strikethrough Strikethrough
  hi! link @markup.underline Underlined
  hi! link @markup.heading Title
  hi! link @markup.quote NONE
  hi! link @markup.math Literal
  hi! link @markup.link Underlined
  hi! link @markup.raw NormalFloat
  hi! link @markup.list PunctuationSpecial
  hi! link @tag Statement
  hi! link @tag.attribute NONE
endif
if has('nvim-0.9')
endif
hi! link debugBreakpoint ModeMsg
hi! link debugPC CursorLine
hi! link diffAdded Added
hi! link diffRemoved Removed
if has('nvim')
  hi! link CmpItemAbbrMatch Bold
  hi! link CmpItemKind NONE
endif
hi! link UndotreeBranch NONE
hi! link coqTerm Keyword
hi! link coqTactic Constant
hi! link coqLtac Constant
hi! link coqTacticKwd Constant
hi! link helpCommand Literal
hi! link helpExample Literal
hi! link helpHyperTextJump Underlined
hi! link helpOption Underlined
hi! link htmlBold Bold
hi! link htmlItalic Italic
hi! link htmlBoldItalic BoldItalic
hi! link htmlStrike Strikethrough
hi! link luaFunction Keyword
hi! link markdownCode NormalFloat
hi! link markdownCodeBlock NormalFloat
hi! link markdownHeadingDelimiter Keyword
hi! link markdownListMarker PunctuationSpecial
hi! link markdownHeadingDelimiter PunctuationSpecial
hi! link ocamlModPath NONE
hi! link ocamlFullMod NONE
hi! link ocamlOperator Operator
hi! link pythonBuiltin Constant
hi! link pythonExceptions NONE
hi! link rustCommentLineDoc Comment
hi! link rustModPath NONE
hi! link shCommandSub NONE
hi! link shArithmetic NONE
hi! link shShellVariables NONE
hi! link shSpecial NONE
hi! link shSpecialDQ NONE
hi! link shSpecialSQ NONE
hi! link texCmd Constant
hi! link texCmdType Constant
hi! link texMathDelim Delimiter
hi! link texMathZone Literal
hi! link texNewcmdArgName Label
hi! link texPartArgTitle Title
hi! link texTitleArg Title
hi! link texZone Literal
hi! link vimAutoEvent Constant
hi! link vimCommentTitle SpecialComment
hi! link vimEnvvar Constant
hi! link vimOption Constant

if &background ==# 'dark'
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#080808', '#d7005f', '#22bf00', '#d79600', '#0080dd', '#d777d7', '#00cccc', '#bcbcbc', '#626262', '#ff2266', '#55ff00', '#ffaf00', '#5fafff', '#ff87ff', '#00eeff', '#eeeeee']
  endif
  if has('nvim')
    let g:terminal_color_0 = '#080808'
    let g:terminal_color_1 = '#d7005f'
    let g:terminal_color_2 = '#22bf00'
    let g:terminal_color_3 = '#d79600'
    let g:terminal_color_4 = '#0080dd'
    let g:terminal_color_5 = '#d777d7'
    let g:terminal_color_6 = '#00cccc'
    let g:terminal_color_7 = '#bcbcbc'
    let g:terminal_color_8 = '#626262'
    let g:terminal_color_9 = '#ff2266'
    let g:terminal_color_10 = '#55ff00'
    let g:terminal_color_11 = '#ffaf00'
    let g:terminal_color_12 = '#5fafff'
    let g:terminal_color_13 = '#ff87ff'
    let g:terminal_color_14 = '#00eeff'
    let g:terminal_color_15 = '#eeeeee'
  endif
  hi Normal guifg=#eeeeee guibg=#080808 gui=NONE cterm=NONE
  hi NormalFloat guifg=NONE guibg=#333333 gui=NONE cterm=NONE
  hi Comment guifg=#bcbcbc guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#ffffff guibg=NONE gui=italic cterm=italic
  hi Identifier guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#eeeeee guibg=NONE gui=bold cterm=bold
  hi Label guifg=#d7afd7 guibg=NONE gui=bold cterm=bold
  hi PreProc guifg=#eeeeee guibg=NONE gui=bold cterm=bold
  hi Macro guifg=#afd7d7 guibg=NONE gui=italic cterm=italic
  hi Type guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#afd7d7 guibg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#d0d0d0 guibg=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#bcbcbc guibg=NONE gui=bold cterm=bold
  hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Ignore guifg=#626262 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#ff005f guibg=#000000 gui=bold,reverse cterm=bold,reverse
  hi Todo guifg=#00ffaf guibg=#000000 gui=bold,reverse cterm=bold,reverse
  hi Added guifg=#22bf00 guibg=NONE gui=NONE cterm=NONE
  hi Changed guifg=#00cccc guibg=NONE gui=NONE cterm=NONE
  hi Removed guifg=#d7005f guibg=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#222222 gui=NONE cterm=NONE
  hi Conceal guifg=#afd7d7 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorIM guifg=#000000 guibg=#afff00 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#444444 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#444444 gui=NONE cterm=NONE
  hi CursorLineNr guifg=NONE guibg=#444444 gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#284028 gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#304848 gui=NONE cterm=NONE
  hi DiffDelete guifg=#d7005f guibg=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#606030 gui=NONE cterm=NONE
  hi Directory guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi ErrorMsg guifg=NONE guibg=NONE gui=bold,reverse ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi FoldColumn guifg=#626262 guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#d0d0d0 guibg=#222222 gui=NONE cterm=NONE
  hi IncSearch guifg=#ffaf00 guibg=#000000 gui=bold,reverse,underline cterm=bold,reverse,underline
  hi LineNr guifg=#bcbcbc guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#ff00af guibg=NONE gui=bold cterm=bold
  hi ModeMsg guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText guifg=#626262 guibg=NONE gui=nocombine cterm=nocombine
  hi Pmenu guifg=NONE guibg=#404868 gui=NONE cterm=NONE
  hi PmenuExtra guifg=NONE guibg=#404868 gui=NONE cterm=NONE
  hi PmenuKind guifg=NONE guibg=#404868 gui=bold cterm=bold
  hi PmenuSbar guifg=NONE guibg=#626262 gui=NONE cterm=NONE
  hi PmenuSel guifg=NONE guibg=#704470 gui=NONE cterm=NONE
  hi PmenuExtraSel guifg=NONE guibg=#704470 gui=NONE cterm=NONE
  hi PmenuKindSel guifg=NONE guibg=#704470 gui=bold cterm=bold
  hi PmenuThumb guifg=#606030 guibg=#704470 gui=NONE cterm=NONE
  hi Question guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi QuickFixLine guifg=NONE guibg=#704470 gui=NONE cterm=NONE
  hi Search guifg=#00afff guibg=#000000 gui=bold,reverse cterm=bold,reverse
  hi CurSearch guifg=#aa22aa guibg=#ffffff gui=bold,reverse,underline cterm=bold,reverse,underline
  hi SignColumn guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#d7005f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#0080dd gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#d777d7 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#00cccc gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine guifg=#080808 guibg=#eeeeee gui=bold cterm=bold
  hi StatusLineNC guifg=#080808 guibg=#626262 gui=NONE cterm=NONE
  hi TabLine guifg=NONE guibg=#626262 gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#444444 gui=NONE cterm=NONE
  hi TabLineSel guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Title guifg=#d7afd7 guibg=NONE gui=bold,underline cterm=bold,underline
  hi Visual guifg=#ffaf00 guibg=#000000 gui=reverse cterm=reverse
  hi VisualNOS guifg=NONE guibg=#444444 gui=NONE cterm=NONE
  hi WarningMsg guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WildMenu guifg=#00afff guibg=NONE gui=bold cterm=bold
  hi WinSeparator guifg=#d0d0d0 guibg=#444444 gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Bold guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Italic guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi BoldItalic guifg=NONE guibg=NONE gui=bold,italic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi Strikethrough guifg=NONE guibg=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
  hi Literal guifg=#d7d7af guibg=NONE gui=NONE cterm=NONE
  hi PunctuationSpecial guifg=#afd7d7 guibg=NONE gui=bold cterm=bold
  hi LspReferenceText guifg=#d0d0d0 guibg=NONE gui=reverse cterm=reverse
  hi LspReferenceRead guifg=#d0d0d0 guibg=NONE gui=reverse cterm=reverse
  hi LspReferenceWrite guifg=#d0d0d0 guibg=NONE gui=reverse cterm=reverse
  hi LspInlayHint guifg=#bcbcbc guibg=#222222 gui=NONE cterm=NONE
  hi LspCodeLens guifg=#bcbcbc guibg=#222222 gui=NONE cterm=NONE
  hi LspCodeLensSeparator guifg=NONE guibg=#222222 gui=bold cterm=bold
  hi DiagnosticError guifg=#d7005f guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticWarn guifg=#d79600 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticInfo guifg=#00cccc guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticHint guifg=#0080dd guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticOk guifg=#22bf00 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#d7005f gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#d79600 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#00cccc gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#0080dd gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#22bf00 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi Sneak guifg=#ffffff guibg=#00afff gui=bold cterm=bold
  hi SneakLabel guifg=#ffffff guibg=#00afff gui=bold cterm=bold
  hi FlashLabel guifg=#000000 guibg=#afff00 gui=bold cterm=bold
  if !s:italics
    hi Constant gui=NONE cterm=NONE
    hi Macro gui=NONE cterm=NONE
    hi Italic gui=NONE cterm=NONE
    hi BoldItalic gui=bold cterm=bold
  endif
else
  " Light background
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#eeeeee', '#af0011', '#177700', '#af7700', '#005faf', '#871087', '#009999', '#626262', '#9e9e9e', '#d70011', '#30af00', '#d79700', '#0087d7', '#af10af', '#00bfbf', '#121212']
  endif
  if has('nvim')
    let g:terminal_color_0 = '#eeeeee'
    let g:terminal_color_1 = '#af0011'
    let g:terminal_color_2 = '#177700'
    let g:terminal_color_3 = '#af7700'
    let g:terminal_color_4 = '#005faf'
    let g:terminal_color_5 = '#871087'
    let g:terminal_color_6 = '#009999'
    let g:terminal_color_7 = '#626262'
    let g:terminal_color_8 = '#9e9e9e'
    let g:terminal_color_9 = '#d70011'
    let g:terminal_color_10 = '#30af00'
    let g:terminal_color_11 = '#d79700'
    let g:terminal_color_12 = '#0087d7'
    let g:terminal_color_13 = '#af10af'
    let g:terminal_color_14 = '#00bfbf'
    let g:terminal_color_15 = '#121212'
  endif
  hi Normal guifg=#121212 guibg=#eeeeee gui=NONE cterm=NONE
  hi NormalFloat guifg=NONE guibg=#c6c6c6 gui=NONE cterm=NONE
  hi Comment guifg=#626262 guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#000000 guibg=NONE gui=italic cterm=italic
  hi Identifier guifg=#121212 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#121212 guibg=NONE gui=bold cterm=bold
  hi Label guifg=#602460 guibg=NONE gui=bold cterm=bold
  hi PreProc guifg=#121212 guibg=NONE gui=bold cterm=bold
  hi Macro guifg=#234e5f guibg=NONE gui=italic cterm=italic
  hi Type guifg=#121212 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#234e5f guibg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#3a3a3a guibg=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#626262 guibg=NONE gui=bold cterm=bold
  hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Ignore guifg=#9e9e9e guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#ff005f guibg=#000000 gui=bold,reverse cterm=bold,reverse
  hi Todo guifg=#00ffaf guibg=#000000 gui=bold,reverse cterm=bold,reverse
  hi Added guifg=#177700 guibg=NONE gui=NONE cterm=NONE
  hi Changed guifg=#009999 guibg=NONE gui=NONE cterm=NONE
  hi Removed guifg=#af0011 guibg=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#dadada gui=NONE cterm=NONE
  hi Conceal guifg=#234e5f guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorIM guifg=#000000 guibg=#afff00 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#b2b2b2 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#b2b2b2 gui=NONE cterm=NONE
  hi CursorLineNr guifg=NONE guibg=#b2b2b2 gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#b7d2b7 gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#afd7d7 gui=NONE cterm=NONE
  hi DiffDelete guifg=#af0011 guibg=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#ddd099 gui=NONE cterm=NONE
  hi Directory guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi ErrorMsg guifg=NONE guibg=NONE gui=bold,reverse ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi FoldColumn guifg=#9e9e9e guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#3a3a3a guibg=#dadada gui=NONE cterm=NONE
  hi IncSearch guifg=#ffaf00 guibg=#000000 gui=bold,reverse,underline cterm=bold,reverse,underline
  hi LineNr guifg=#626262 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#ff00af guibg=NONE gui=bold cterm=bold
  hi ModeMsg guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText guifg=#9e9e9e guibg=NONE gui=nocombine cterm=nocombine
  hi Pmenu guifg=NONE guibg=#a0afd7 gui=NONE cterm=NONE
  hi PmenuExtra guifg=NONE guibg=#a0afd7 gui=NONE cterm=NONE
  hi PmenuKind guifg=NONE guibg=#a0afd7 gui=bold cterm=bold
  hi PmenuSbar guifg=NONE guibg=#9e9e9e gui=NONE cterm=NONE
  hi PmenuSel guifg=NONE guibg=#d7a0d7 gui=NONE cterm=NONE
  hi PmenuExtraSel guifg=NONE guibg=#d7a0d7 gui=NONE cterm=NONE
  hi PmenuKindSel guifg=NONE guibg=#d7a0d7 gui=bold cterm=bold
  hi PmenuThumb guifg=#ddd099 guibg=#d7a0d7 gui=NONE cterm=NONE
  hi Question guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi QuickFixLine guifg=NONE guibg=#d7a0d7 gui=NONE cterm=NONE
  hi Search guifg=#00afff guibg=#000000 gui=bold,reverse cterm=bold,reverse
  hi CurSearch guifg=#ff5fff guibg=#000000 gui=bold,reverse,underline cterm=bold,reverse,underline
  hi SignColumn guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#af0011 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#005faf gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#871087 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#009999 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine guifg=#eeeeee guibg=#121212 gui=bold cterm=bold
  hi StatusLineNC guifg=#eeeeee guibg=#9e9e9e gui=NONE cterm=NONE
  hi TabLine guifg=NONE guibg=#9e9e9e gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#b2b2b2 gui=NONE cterm=NONE
  hi TabLineSel guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Title guifg=#602460 guibg=NONE gui=bold,underline cterm=bold,underline
  hi Visual guifg=#ffaf00 guibg=#000000 gui=reverse cterm=reverse
  hi VisualNOS guifg=NONE guibg=#b2b2b2 gui=NONE cterm=NONE
  hi WarningMsg guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WildMenu guifg=#00afff guibg=NONE gui=bold cterm=bold
  hi WinSeparator guifg=#3a3a3a guibg=#b2b2b2 gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Bold guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Italic guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi BoldItalic guifg=NONE guibg=NONE gui=bold,italic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi Strikethrough guifg=NONE guibg=NONE gui=strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
  hi Literal guifg=#5c5c23 guibg=NONE gui=NONE cterm=NONE
  hi PunctuationSpecial guifg=#234e5f guibg=NONE gui=bold cterm=bold
  hi LspReferenceText guifg=#3a3a3a guibg=NONE gui=reverse cterm=reverse
  hi LspReferenceRead guifg=#3a3a3a guibg=NONE gui=reverse cterm=reverse
  hi LspReferenceWrite guifg=#3a3a3a guibg=NONE gui=reverse cterm=reverse
  hi LspInlayHint guifg=#626262 guibg=#dadada gui=NONE cterm=NONE
  hi LspCodeLens guifg=#626262 guibg=#dadada gui=NONE cterm=NONE
  hi LspCodeLensSeparator guifg=NONE guibg=#dadada gui=bold cterm=bold
  hi DiagnosticError guifg=#af0011 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticWarn guifg=#af7700 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticInfo guifg=#009999 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticHint guifg=#005faf guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticOk guifg=#177700 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#af0011 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#af7700 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#009999 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#005faf gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineOk guifg=NONE guibg=NONE guisp=#177700 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi Sneak guifg=#ffffff guibg=#00afff gui=bold cterm=bold
  hi SneakLabel guifg=#ffffff guibg=#00afff gui=bold cterm=bold
  hi FlashLabel guifg=#000000 guibg=#afff00 gui=bold cterm=bold
  if !s:italics
    hi Constant gui=NONE cterm=NONE
    hi Macro gui=NONE cterm=NONE
    hi Italic gui=NONE cterm=NONE
    hi BoldItalic gui=bold cterm=bold
  endif
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    hi Normal ctermfg=255 ctermbg=232 cterm=NONE
    hi NormalFloat ctermfg=NONE ctermbg=236 cterm=NONE
    hi Comment ctermfg=250 ctermbg=NONE cterm=NONE
    hi Constant ctermfg=231 ctermbg=NONE cterm=italic
    hi Identifier ctermfg=255 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=255 ctermbg=NONE cterm=bold
    hi Label ctermfg=182 ctermbg=NONE cterm=bold
    hi PreProc ctermfg=255 ctermbg=NONE cterm=bold
    hi Macro ctermfg=152 ctermbg=NONE cterm=italic
    hi Type ctermfg=255 ctermbg=NONE cterm=NONE
    hi Special ctermfg=152 ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=252 ctermbg=NONE cterm=NONE
    hi SpecialComment ctermfg=250 ctermbg=NONE cterm=bold
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi Ignore ctermfg=241 ctermbg=NONE cterm=NONE
    hi Error ctermfg=197 ctermbg=16 cterm=bold,reverse
    hi Todo ctermfg=49 ctermbg=16 cterm=bold,reverse
    hi Added ctermfg=34 ctermbg=NONE cterm=NONE
    hi Changed ctermfg=44 ctermbg=NONE cterm=NONE
    hi Removed ctermfg=161 ctermbg=NONE cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=235 cterm=NONE
    hi Conceal ctermfg=152 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi CursorIM ctermfg=16 ctermbg=154 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=238 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=238 cterm=NONE
    hi CursorLineNr ctermfg=NONE ctermbg=238 cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=22 cterm=NONE
    hi DiffChange ctermfg=NONE ctermbg=23 cterm=NONE
    hi DiffDelete ctermfg=161 ctermbg=NONE cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=58 cterm=NONE
    hi Directory ctermfg=NONE ctermbg=NONE cterm=bold
    hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=bold,reverse
    hi FoldColumn ctermfg=241 ctermbg=NONE cterm=NONE
    hi Folded ctermfg=252 ctermbg=235 cterm=NONE
    hi IncSearch ctermfg=214 ctermbg=16 cterm=bold,reverse,underline
    hi LineNr ctermfg=250 ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=199 ctermbg=NONE cterm=bold
    hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi NonText ctermfg=241 ctermbg=NONE cterm=nocombine
    hi Pmenu ctermfg=NONE ctermbg=60 cterm=NONE
    hi PmenuExtra ctermfg=NONE ctermbg=60 cterm=NONE
    hi PmenuKind ctermfg=NONE ctermbg=60 cterm=bold
    hi PmenuSbar ctermfg=NONE ctermbg=241 cterm=NONE
    hi PmenuSel ctermfg=NONE ctermbg=96 cterm=NONE
    hi PmenuExtraSel ctermfg=NONE ctermbg=96 cterm=NONE
    hi PmenuKindSel ctermfg=NONE ctermbg=96 cterm=bold
    hi PmenuThumb ctermfg=58 ctermbg=96 cterm=NONE
    hi Question ctermfg=NONE ctermbg=NONE cterm=bold
    hi QuickFixLine ctermfg=NONE ctermbg=96 cterm=NONE
    hi Search ctermfg=39 ctermbg=16 cterm=bold,reverse
    hi CurSearch ctermfg=127 ctermbg=231 cterm=bold,reverse,underline
    hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi StatusLine ctermfg=232 ctermbg=255 cterm=bold
    hi StatusLineNC ctermfg=232 ctermbg=241 cterm=NONE
    hi TabLine ctermfg=NONE ctermbg=241 cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=238 cterm=NONE
    hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=bold
    hi Title ctermfg=182 ctermbg=NONE cterm=bold,underline
    hi Visual ctermfg=214 ctermbg=16 cterm=reverse
    hi VisualNOS ctermfg=NONE ctermbg=238 cterm=NONE
    hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=39 ctermbg=NONE cterm=bold
    hi WinSeparator ctermfg=252 ctermbg=238 cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold
    hi Bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi Italic ctermfg=NONE ctermbg=NONE cterm=italic
    hi BoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
    hi Strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
    hi Literal ctermfg=187 ctermbg=NONE cterm=NONE
    hi PunctuationSpecial ctermfg=152 ctermbg=NONE cterm=bold
    hi LspReferenceText ctermfg=252 ctermbg=NONE cterm=reverse
    hi LspReferenceRead ctermfg=252 ctermbg=NONE cterm=reverse
    hi LspReferenceWrite ctermfg=252 ctermbg=NONE cterm=reverse
    hi LspInlayHint ctermfg=250 ctermbg=235 cterm=NONE
    hi LspCodeLens ctermfg=250 ctermbg=235 cterm=NONE
    hi LspCodeLensSeparator ctermfg=NONE ctermbg=235 cterm=bold
    hi DiagnosticError ctermfg=161 ctermbg=NONE cterm=NONE
    hi DiagnosticWarn ctermfg=172 ctermbg=NONE cterm=NONE
    hi DiagnosticInfo ctermfg=44 ctermbg=NONE cterm=NONE
    hi DiagnosticHint ctermfg=32 ctermbg=NONE cterm=NONE
    hi DiagnosticOk ctermfg=34 ctermbg=NONE cterm=NONE
    hi DiagnosticUnderlineError ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineWarn ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineHint ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineOk ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi Sneak ctermfg=231 ctermbg=39 cterm=bold
    hi SneakLabel ctermfg=231 ctermbg=39 cterm=bold
    hi FlashLabel ctermfg=16 ctermbg=154 cterm=bold
    if !s:italics
      hi Constant cterm=NONE
      hi Macro cterm=NONE
      hi Italic cterm=NONE
      hi BoldItalic cterm=bold
    endif
  else
    " Light background
    hi Normal ctermfg=233 ctermbg=255 cterm=NONE
    hi NormalFloat ctermfg=NONE ctermbg=251 cterm=NONE
    hi Comment ctermfg=241 ctermbg=NONE cterm=NONE
    hi Constant ctermfg=16 ctermbg=NONE cterm=italic
    hi Identifier ctermfg=233 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=233 ctermbg=NONE cterm=bold
    hi Label ctermfg=53 ctermbg=NONE cterm=bold
    hi PreProc ctermfg=233 ctermbg=NONE cterm=bold
    hi Macro ctermfg=23 ctermbg=NONE cterm=italic
    hi Type ctermfg=233 ctermbg=NONE cterm=NONE
    hi Special ctermfg=23 ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=237 ctermbg=NONE cterm=NONE
    hi SpecialComment ctermfg=241 ctermbg=NONE cterm=bold
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi Ignore ctermfg=247 ctermbg=NONE cterm=NONE
    hi Error ctermfg=197 ctermbg=16 cterm=bold,reverse
    hi Todo ctermfg=49 ctermbg=16 cterm=bold,reverse
    hi Added ctermfg=28 ctermbg=NONE cterm=NONE
    hi Changed ctermfg=30 ctermbg=NONE cterm=NONE
    hi Removed ctermfg=124 ctermbg=NONE cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=253 cterm=NONE
    hi Conceal ctermfg=23 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi CursorIM ctermfg=16 ctermbg=154 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=249 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=249 cterm=NONE
    hi CursorLineNr ctermfg=NONE ctermbg=249 cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=151 cterm=NONE
    hi DiffChange ctermfg=NONE ctermbg=152 cterm=NONE
    hi DiffDelete ctermfg=124 ctermbg=NONE cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=186 cterm=NONE
    hi Directory ctermfg=NONE ctermbg=NONE cterm=bold
    hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=bold,reverse
    hi FoldColumn ctermfg=247 ctermbg=NONE cterm=NONE
    hi Folded ctermfg=237 ctermbg=253 cterm=NONE
    hi IncSearch ctermfg=214 ctermbg=16 cterm=bold,reverse,underline
    hi LineNr ctermfg=241 ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=199 ctermbg=NONE cterm=bold
    hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi NonText ctermfg=247 ctermbg=NONE cterm=nocombine
    hi Pmenu ctermfg=NONE ctermbg=146 cterm=NONE
    hi PmenuExtra ctermfg=NONE ctermbg=146 cterm=NONE
    hi PmenuKind ctermfg=NONE ctermbg=146 cterm=bold
    hi PmenuSbar ctermfg=NONE ctermbg=247 cterm=NONE
    hi PmenuSel ctermfg=NONE ctermbg=176 cterm=NONE
    hi PmenuExtraSel ctermfg=NONE ctermbg=176 cterm=NONE
    hi PmenuKindSel ctermfg=NONE ctermbg=176 cterm=bold
    hi PmenuThumb ctermfg=186 ctermbg=176 cterm=NONE
    hi Question ctermfg=NONE ctermbg=NONE cterm=bold
    hi QuickFixLine ctermfg=NONE ctermbg=176 cterm=NONE
    hi Search ctermfg=39 ctermbg=16 cterm=bold,reverse
    hi CurSearch ctermfg=207 ctermbg=16 cterm=bold,reverse,underline
    hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi StatusLine ctermfg=255 ctermbg=233 cterm=bold
    hi StatusLineNC ctermfg=255 ctermbg=247 cterm=NONE
    hi TabLine ctermfg=NONE ctermbg=247 cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=249 cterm=NONE
    hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=bold
    hi Title ctermfg=53 ctermbg=NONE cterm=bold,underline
    hi Visual ctermfg=214 ctermbg=16 cterm=reverse
    hi VisualNOS ctermfg=NONE ctermbg=249 cterm=NONE
    hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=39 ctermbg=NONE cterm=bold
    hi WinSeparator ctermfg=237 ctermbg=249 cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold
    hi Bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi Italic ctermfg=NONE ctermbg=NONE cterm=italic
    hi BoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
    hi Strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
    hi Literal ctermfg=58 ctermbg=NONE cterm=NONE
    hi PunctuationSpecial ctermfg=23 ctermbg=NONE cterm=bold
    hi LspReferenceText ctermfg=237 ctermbg=NONE cterm=reverse
    hi LspReferenceRead ctermfg=237 ctermbg=NONE cterm=reverse
    hi LspReferenceWrite ctermfg=237 ctermbg=NONE cterm=reverse
    hi LspInlayHint ctermfg=241 ctermbg=253 cterm=NONE
    hi LspCodeLens ctermfg=241 ctermbg=253 cterm=NONE
    hi LspCodeLensSeparator ctermfg=NONE ctermbg=253 cterm=bold
    hi DiagnosticError ctermfg=124 ctermbg=NONE cterm=NONE
    hi DiagnosticWarn ctermfg=136 ctermbg=NONE cterm=NONE
    hi DiagnosticInfo ctermfg=30 ctermbg=NONE cterm=NONE
    hi DiagnosticHint ctermfg=25 ctermbg=NONE cterm=NONE
    hi DiagnosticOk ctermfg=28 ctermbg=NONE cterm=NONE
    hi DiagnosticUnderlineError ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineWarn ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineHint ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineOk ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi Sneak ctermfg=231 ctermbg=39 cterm=bold
    hi SneakLabel ctermfg=231 ctermbg=39 cterm=bold
    hi FlashLabel ctermfg=16 ctermbg=154 cterm=bold
    if !s:italics
      hi Constant cterm=NONE
      hi Macro cterm=NONE
      hi Italic cterm=NONE
      hi BoldItalic cterm=bold
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 16
  if has('nvim-0.8')
    hi! link @markup.raw Comment
  endif
  hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NormalFloat ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Comment ctermfg=8 ctermbg=NONE cterm=bold
  hi Constant ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Statement ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Label ctermfg=NONE ctermbg=NONE cterm=bold
  hi PreProc ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Macro ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Type ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Special ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=NONE ctermbg=NONE cterm=italic
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Error ctermfg=darkred ctermbg=NONE cterm=bold,reverse
  hi Todo ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Added ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi Changed ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi Removed ctermfg=darkred ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=8 ctermbg=NONE cterm=reverse
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorLineNr ctermfg=NONE ctermbg=NONE cterm=bold
  hi DiffAdd ctermfg=darkgreen ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=darkblue ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=darkred ctermbg=NONE cterm=NONE
  hi DiffText ctermfg=darkmagenta ctermbg=NONE cterm=reverse
  hi Directory ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi FoldColumn ctermfg=8 ctermbg=NONE cterm=reverse
  hi Folded ctermfg=NONE ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=darkyellow ctermbg=NONE cterm=bold,reverse,underline
  hi LineNr ctermfg=8 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText ctermfg=8 ctermbg=NONE cterm=nocombine
  hi Pmenu ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuExtra ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuKind ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuSel ctermfg=8 ctermbg=NONE cterm=bold,reverse,underline
  hi PmenuExtraSel ctermfg=8 ctermbg=NONE cterm=bold,reverse
  hi PmenuKindSel ctermfg=8 ctermbg=NONE cterm=bold,reverse
  hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question ctermfg=NONE ctermbg=NONE cterm=bold
  hi QuickFixLine ctermfg=darkmagenta ctermbg=NONE cterm=reverse
  hi Search ctermfg=darkcyan ctermbg=NONE cterm=bold,reverse
  hi CurSearch ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse,underline
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=reverse
  if !s:italics
    hi SpecialComment cterm=NONE
  endif
  if has('nvim')
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  else
    hi SpellBad ctermfg=darkred ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=darkblue ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=darkmagenta ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=darkcyan ctermbg=NONE cterm=undercurl
  endif
  hi StatusLine ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi StatusLineNC ctermfg=8 ctermbg=NONE cterm=bold,reverse
  hi TabLine ctermfg=NONE ctermbg=8 cterm=bold
  hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=underline
  hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi Title ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi VertSplit ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual ctermfg=darkyellow ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=standout
  hi WildMenu ctermfg=NONE ctermbg=NONE cterm=bold
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi BoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi Strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
  hi Literal ctermfg=NONE ctermbg=NONE cterm=italic
  hi PunctuationSpecial ctermfg=NONE ctermbg=NONE cterm=bold
  hi LspReferenceText ctermfg=8 ctermbg=NONE cterm=reverse
  hi LspReferenceRead ctermfg=8 ctermbg=NONE cterm=reverse
  hi LspReferenceWrite ctermfg=8 ctermbg=NONE cterm=reverse
  hi LspInlayHint ctermfg=8 ctermbg=NONE cterm=reverse
  hi LspCodeLens ctermfg=8 ctermbg=NONE cterm=reverse
  hi LspCodeLensSeparator ctermfg=8 ctermbg=NONE cterm=bold,reverse
  hi DiagnosticError ctermfg=darkred ctermbg=NONE cterm=NONE
  hi DiagnosticWarn ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi DiagnosticInfo ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi DiagnosticHint ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi DiagnosticOk ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi DiagnosticUnderlineError ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineWarn ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineHint ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineOk ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi Sneak ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi SneakLabel ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi FlashLabel ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi FlashBackdrop ctermfg=NONE ctermbg=NONE cterm=NONE
  if !s:italics
    hi Italic cterm=NONE
    hi BoldItalic cterm=bold
    hi Literal cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if has('nvim-0.8')
    hi! link @markup.raw Comment
  endif
  hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NormalFloat ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Comment ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi Constant ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Statement ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Label ctermfg=NONE ctermbg=NONE cterm=bold
  hi PreProc ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Macro ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Type ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Special ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=NONE ctermbg=NONE cterm=italic
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Error ctermfg=darkred ctermbg=NONE cterm=bold,reverse
  hi Todo ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Added ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi Changed ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi Removed ctermfg=darkred ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorLineNr ctermfg=NONE ctermbg=NONE cterm=bold
  hi DiffAdd ctermfg=darkgreen ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=darkblue ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=darkred ctermbg=NONE cterm=NONE
  hi DiffText ctermfg=darkmagenta ctermbg=NONE cterm=reverse
  hi Directory ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi FoldColumn ctermfg=NONE ctermbg=NONE cterm=reverse
  hi Folded ctermfg=NONE ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=darkyellow ctermbg=NONE cterm=bold,reverse,underline
  hi LineNr ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=NONE ctermbg=NONE cterm=NONE
  hi NonText ctermfg=darkyellow ctermbg=NONE cterm=nocombine
  hi Pmenu ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuExtra ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuKind ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=reverse
  hi PmenuSel ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi PmenuExtraSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi PmenuKindSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi PmenuThumb ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Question ctermfg=NONE ctermbg=NONE cterm=bold
  hi QuickFixLine ctermfg=darkmagenta ctermbg=NONE cterm=reverse
  hi Search ctermfg=darkcyan ctermbg=NONE cterm=bold,reverse
  hi CurSearch ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse,underline
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=reverse
  if !s:italics
    hi Comment cterm=bold
    hi SpecialComment cterm=NONE
  endif
  if has('nvim')
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  else
    hi SpellBad ctermfg=darkred ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=darkblue ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=darkmagenta ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=darkcyan ctermbg=NONE cterm=undercurl
  endif
  hi StatusLine ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi StatusLineNC ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi TabLine ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi TabLineFill ctermfg=NONE ctermbg=NONE cterm=underline
  hi TabLineSel ctermfg=NONE ctermbg=NONE cterm=bold
  hi Title ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi VertSplit ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual ctermfg=darkyellow ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=standout
  hi WildMenu ctermfg=NONE ctermbg=NONE cterm=bold
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarButton ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi BoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi Strikethrough ctermfg=NONE ctermbg=NONE cterm=strikethrough
  hi Literal ctermfg=NONE ctermbg=NONE cterm=italic
  hi PunctuationSpecial ctermfg=NONE ctermbg=NONE cterm=bold
  hi LspReferenceText ctermfg=NONE ctermbg=NONE cterm=reverse
  hi LspReferenceRead ctermfg=NONE ctermbg=NONE cterm=reverse
  hi LspReferenceWrite ctermfg=NONE ctermbg=NONE cterm=reverse
  hi LspInlayHint ctermfg=NONE ctermbg=NONE cterm=reverse
  hi LspCodeLens ctermfg=NONE ctermbg=NONE cterm=reverse
  hi LspCodeLensSeparator ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi DiagnosticError ctermfg=darkred ctermbg=NONE cterm=NONE
  hi DiagnosticWarn ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi DiagnosticInfo ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi DiagnosticHint ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi DiagnosticOk ctermfg=darkgreen ctermbg=NONE cterm=NONE
  hi DiagnosticUnderlineError ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineWarn ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineHint ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi DiagnosticUnderlineOk ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi Sneak ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi SneakLabel ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi FlashLabel ctermfg=darkmagenta ctermbg=NONE cterm=bold,reverse
  hi FlashBackdrop ctermfg=NONE ctermbg=NONE cterm=NONE
  if !s:italics
    hi Italic cterm=NONE
    hi BoldItalic cterm=bold
    hi Literal cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi NormalFloat term=reverse
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=reverse
  hi CursorColumn term=NONE
  hi CursorLine term=underline
  hi CursorLineNr term=bold
  hi DiffAdd term=reverse
  hi DiffChange term=NONE
  hi DiffDelete term=reverse
  hi DiffText term=reverse
  hi Directory term=NONE
  hi ErrorMsg term=bold,reverse
  hi FoldColumn term=NONE
  hi Folded term=NONE
  hi IncSearch term=bold,reverse,underline
  hi LineNr term=NONE
  hi MatchParen term=bold,underline
  hi ModeMsg term=bold
  hi MoreMsg term=NONE
  hi NonText term=nocombine
  hi Pmenu term=reverse
  hi PmenuSbar term=reverse
  hi PmenuSel term=bold
  hi PmenuThumb term=NONE
  hi Question term=bold
  hi Search term=reverse
  hi SignColumn term=reverse
  hi SpellBad term=underline
  hi SpellCap term=underline
  hi SpellLocal term=underline
  hi SpellRare term=underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=bold,underline
  hi TabLine term=bold,underline
  hi TabLineFill term=NONE
  hi Terminal term=NONE
  hi TabLineSel term=bold,reverse
  hi Title term=NONE
  hi VertSplit term=NONE
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  hi CurSearch term=reverse
  hi CursorLineFold term=underline
  hi CursorLineSign term=underline
  hi Comment term=bold
  hi Constant term=NONE
  hi Error term=bold,reverse
  hi Identifier term=NONE
  hi Ignore term=NONE
  hi PreProc term=NONE
  hi Special term=NONE
  hi Statement term=NONE
  hi Todo term=bold,reverse
  hi Type term=NONE
  hi Underlined term=underline
  unlet s:t_Co s:italics
  finish
endif

" Color: black         #000000           16
" Color: white         #ffffff           231
" Background: dark
" Color: fg_1          #ffffff           231
" Color: fg0           #eeeeee           255
" Color: fg1           #d0d0d0           252
" Color: fg2           #bcbcbc           250
" Color: bg0           #080808           232
" Color: bg1           #222222           235
" Color: bg2           #333333           236
" Color: bg3           #444444           238
" Color: bg4           #626262           241
" Color: quite1        #d7005f           161
" Color: quite2        #22bf00           34
" Color: quite3        #d79600           172
" Color: quite4        #0080dd           32
" Color: quite5        #d777d7           176
" Color: quite6        #00cccc           44
" Color: quite9        #ff2266           197
" Color: quite10       #55ff00           82
" Color: quite11       #ffaf00           214
" Color: quite12       #5fafff           75
" Color: quite13       #ff87ff           213
" Color: quite14       #00eeff           87
" Color: bggreen       #284028           22
" Color: bgblue        #404868           60
" Color: bgpink        #704470           96
" Color: bgyellow      #606030           58
" Color: bgcyan        #304848           23
" Color: uipink        #ff00af           199
" Color: uilime        #afff00           154
" Color: uiteal        #00ffaf           49
" Color: uiblue        #00afff           39
" Color: uipurple      #af00ff           129
" Color: uiamber       #ffaf00           214
" Color: uicursearch   #aa22aa           127
" Color: specialcyan   #afd7d7           152
" Color: literalyellow #d7d7af           187
" Color: labelpink     #d7afd7           182
" Color: errorred      #ff005f           197
" Term colors: bg0
" Term colors: quite1 quite2 quite3 quite4 quite5 quite6
" Term colors: fg2
" Term colors: bg4
" Term colors: quite9 quite10 quite11 quite12 quite13 quite14
" Term colors: fg0
" Background: light
" Color: fg_1          #000000           16
" Color: fg0           #121212           233
" Color: fg1           #3a3a3a           237
" Color: fg2           #626262           241
" Color: bg0           #eeeeee           255
" Color: bg1           #dadada           253
" Color: bg2           #c6c6c6           251
" Color: bg3           #b2b2b2           249
" Color: bg4           #9e9e9e           247
" Color: quite1        #af0011           124
" Color: quite2        #177700           28
" Color: quite3        #af7700           136
" Color: quite4        #005faf           25
" Color: quite5        #871087           90
" Color: quite6        #009999           30
" Color: quite9        #d70011           160
" Color: quite10       #30af00           34
" Color: quite11       #d79700           172
" Color: quite12       #0087d7           32
" Color: quite13       #af10af           127
" Color: quite14       #00bfbf           37
" Color: bggreen       #b7d2b7           151
" Color: bgblue        #a0afd7           146
" Color: bgpink        #d7a0d7           176
" Color: bgyellow      #ddd099           186
" Color: bgcyan        #afd7d7           152
" Color: uipink        #ff00af           199
" Color: uilime        #afff00           154
" Color: uiteal        #00ffaf           49
" Color: uiblue        #00afff           39
" Color: uipurple      #af00ff           129
" Color: uiamber       #ffaf00           214
" Color: uicursearch   #ff5fff           207
" Color: specialcyan   #234e5f           23
" Color: literalyellow #5c5c23           58
" Color: labelpink     #602460           53
" Color: errorred      #ff005f           197
" Term colors: bg0
" Term colors: quite1 quite2 quite3 quite4 quite5 quite6
" Term colors: fg2
" Term colors: bg4
" Term colors: quite9 quite10 quite11 quite12 quite13 quite14
" Term colors: fg0
" Background: any
" Color: term1         #d7005f           161               darkred
" Color: term2         #22bf00           34                darkgreen
" Color: term3         #d79600           172               darkyellow
" Color: term4         #0080dd           32                darkblue
" Color: term5         #d777d7           176               darkmagenta
" Color: term6         #00cccc           44                darkcyan
" Color: term8         #808080           8                 8  ; darkgrey
" vim: et ts=8 sw=2 sts=2
